version: "3.7"

services:
    webapp:
        links:
            - "mongo"
            - "redis"
        depends_on:
            - "mongo"
            - "redis"
        build:
            context: .
        ports:
            - "4000:4000"
        restart: always
        networks:
            - my-network

    scripts:
        links:
            - "mongo"
        depends_on:
            - "mongo"
        build:
            context: .
        entrypoint: "yarn ingest && cron -f"
        restart: on-failure
        networks:
            - my-network

    mongo:
        image: mongo
        ports:
            - "27017:27017"
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
        networks:
            - my-network

    redis:
        image: redis
        ports:
            - "6379:6379"
        restart: always
        build:
            context: .
            dockerfile: Dockerfile-redis
        networks:
            - my-network

networks:
    my-network:
        driver: "bridge"
